// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnlfA7WKvdMtVplL8R3N_vWflJw8gyCJE',
    appId: '1:383078915759:web:506a8cb13912ec91ed7e5a',
    messagingSenderId: '383078915759',
    projectId: 'fan-page-96c07',
    authDomain: 'fan-page-96c07.firebaseapp.com',
    storageBucket: 'fan-page-96c07.appspot.com',
    measurementId: 'G-ES0WSN6BF1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDetdMk5u9YFT1V2cOGasRDMXnXrtmjMls',
    appId: '1:383078915759:ios:8caeeb2aee5127a2ed7e5a',
    messagingSenderId: '383078915759',
    projectId: 'fan-page-96c07',
    storageBucket: 'fan-page-96c07.appspot.com',
    iosClientId: '383078915759-ao6m49qi6f6jv0548rosrhe8rc4evh3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
